# Numpy
## Ejercicios prácticos

---
### Utiliza Python y Numpy para realizar las siguientes operaciones:
1. Dado el arreglo `a = np.array([1, 2, 3, 4])`, determina si ninguno de los elementos es cero.
2. Dado el arreglo `a = np.array([0, 0, 2, 0])`, determina si contiene algún elemento que no sea cero.
3. Analiza el arreglo `a = np.array([1, 2, np.nan, np.inf])` y determina si contiene valores que sean infinitos o valores no numéricos (NaN).
4. Dado el arreglo `a = np.array([1, 2, np.inf])`, determina si contiene valores infinitos.
5. Dado el arreglo `a = np.array([1, np.nan, 3])`, determina si contiene valores NaN.
6. Dados los arreglos `a = np.array([1, 3, 5])` y `b = np.array([2, 3, 4])`, realiza una comparación elemento a elemento contemplando mayor, mayor o igual, menor y menor o igual.
7. Crea un arreglo que contenga los valores 1, 7, 13 y 105, y determina la cantidad de memoria que ocupa el arreglo.
8. Crea un arreglo de 10 ceros; uno de 10 unos; y uno de 10 cincos.
9. Crea un arreglo que contenga todos los números enteros entre 30 y 70.
10. Crea un arreglo que contenga los números pares entre 30 y 70.
11. Crea una matriz identidad de 3x3.
12. Genera un número aleatorio entre 0 y 1.
13. Crea un arreglo de 15 números aleatorios tomados de una distribución normal estándar.
14. Crea un arreglo con valores entre 15 y 55, e imprime todos los valores excepto el primero y el último.
15. Crea un vector (arreglo) de longitud 10 con valores equitativamente distribuidos entre 5 y 50.
16. Crea un vector con valores de 0 a 20, y cambia el signo de los números de 9 a 15.
17. Convierte el arreglo `a = np.array([1, 2, 3])` a una lista de Python.
18. Convierte la lista `l = [1, 2, 3]` a un arreglo de Numpy.
19. Dada la matriz `m = np.array([[1, 2], [3, 4]])`, verifica qué números son pares y almacena los resultados en otra matriz.
20. Dado el arreglo `m = np.array([[1, 2, 3], [4, 5, 6]])`, encuentra el número de filas y columnas de la matriz.

In [2]:
import numpy as np

In [7]:
# ejercicio 1. Definir el arreglo
a = np.array([1, 2, 3, 4])

# 2. Determinar si ninguno de los elementos es cero.
# np.all(): Comprueba si TODOS los resultados de la condición son True.
resultado = np.all(a != 0)

print("Arreglo a:", a)
print("¿Ningún elemento es cero? (Resultado de np.all(a != 0)):", resultado)

Arreglo a: [1 2 3 4]
¿Ningún elemento es cero? (Resultado de np.all(a != 0)): True


In [8]:
# ejercicio 1 
b= a>0
b

array([ True,  True,  True,  True])

In [3]:
# ejercicio 2

# 1. Definir el arreglo
a = np.array([1, 0, 2, 0])

# 2. Usar np.any() para determinar si algún elemento NO es cero
resultado = np.any(a != 0)

print("Arreglo a:", a)
print("¿Contiene algún elemento que no sea cero?", resultado)

Arreglo a: [1 0 2 0]
¿Contiene algún elemento que no sea cero? True


In [4]:
# ejercicio 3

# 1. Definir el arreglo
a = np.array([1, 2, np.nan, np.inf])

# 2. Crear las condiciones booleanas
es_infinito = np.isinf(a) 
es_nan = np.isnan(a) 

# 3. Combinar las condiciones con OR (|) y verificar si ALGUNO es True con np.any()
resultado = np.any(es_infinito | es_nan)

print("Arreglo a:", a)
print("¿Contiene valores infinitos o NaN?:", resultado)

Arreglo a: [ 1.  2. nan inf]
¿Contiene valores infinitos o NaN?: True


In [5]:
# ejercicio 4

# 1. Definir el arreglo
a = np.array([1, 2, np.inf])

resultado = np.any(np.isinf(a))

print("Arreglo a:", a)
print("¿Contiene valores infinitos? (Resultado de np.any(np.isinf(a))):", resultado)

Arreglo a: [ 1.  2. inf]
¿Contiene valores infinitos? (Resultado de np.any(np.isinf(a))): True


In [6]:
# ejercicio 5

a = np.array([1, np.nan, 3])

resultado = np.any(np.isnan(a))

print("Arreglo a:", a)
print("¿Contiene valores NaN? (Resultado de np.any(np.isnan(a))):", resultado)

Arreglo a: [ 1. nan  3.]
¿Contiene valores NaN? (Resultado de np.any(np.isnan(a))): True


In [7]:
# ejercicio 6 

a = np.array([1, 3, 5])
b = np.array([2, 3, 4])

print("Arreglo a:", a)
print("Arreglo b:", b)
print("-" * 10)

# 2. Realizar las comparaciones
# a > b (Mayor que)
mayor_que = a > b
print("a > b (Mayor que):        ", mayor_que)

# a >= b (Mayor o igual que)
mayor_o_igual_que = a >= b
print("a >= b (Mayor o igual que): ", mayor_o_igual_que)

# a < b (Menor que)
menor_que = a < b
print("a < b (Menor que):        ", menor_que)

# a <= b (Menor o igual que)
menor_o_igual_que = a <= b
print("a <= b (Menor o igual que): ", menor_o_igual_que)

Arreglo a: [1 3 5]
Arreglo b: [2 3 4]
----------
a > b (Mayor que):         [False False  True]
a >= b (Mayor o igual que):  [False  True  True]
a < b (Menor que):         [ True False False]
a <= b (Menor o igual que):  [ True  True False]


In [8]:

# ejercicio 7 

# 1. Crear el arreglo
a = np.array([1, 7, 13, 105])

memoria_total = a.itemsize * a.size

print("Arreglo a:", a)
print("Tipo de dato (dtype):", a.dtype)
print("Tamaño de cada elemento (bytes):", a.itemsize)
print("Número total de elementos:", a.size)
print("-" * 40)
print(f"Memoria total ocupada por el arreglo: {memoria_total} bytes")

Arreglo a: [  1   7  13 105]
Tipo de dato (dtype): int64
Tamaño de cada elemento (bytes): 8
Número total de elementos: 4
----------------------------------------
Memoria total ocupada por el arreglo: 32 bytes


In [9]:
# ejercicio 8 

a = np.arange(30, 71)

print("Arreglo resultante:", a)
print("Forma del arreglo (cantidad de elementos):", a.shape)

Arreglo resultante: [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]
Forma del arreglo (cantidad de elementos): (41,)


In [11]:
# ejercicio 9 

# Empezar en 31 (el número después de 30)
# Terminar en 70 (el número antes de 70)
a = np.arange(31, 70)

print("Arreglo resultante (excluyendo 30 y 70):", a)
print("Primer elemento:", a[0])
print("Último elemento:", a[-1]) 

Arreglo resultante (excluyendo 30 y 70): [31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54
 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]
Primer elemento: 31
Último elemento: 69


In [12]:
# ejercicio 10

a_pares = np.arange(32, 70, 2)

print("Arreglo de números pares entre 30 y 70:", a_pares)
print("Primer elemento:", a_pares[0])   # 32
print("Último elemento:", a_pares[-1])  # 68

Arreglo de números pares entre 30 y 70: [32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]
Primer elemento: 32
Último elemento: 68


In [13]:
# ejercicio 11

# Crea una matriz identidad de 3x3
identidad_3x3 = np.identity(3)

print("Matriz Identidad 3x3:")
print(identidad_3x3)

Matriz Identidad 3x3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
# ejercicio 12 

# Genera un solo número decimal aleatorio entre [0.0 y 1.0)
numero_aleatorio = np.random.random()

print("Número aleatorio entre 0 y 1:", numero_aleatorio)

Número aleatorio entre 0 y 1: 0.017990019996245166


In [15]:
# ejercicio 13

a_normal = np.random.randn(15)

print("Arreglo de 15 números con distribución normal estándar:")
print(a_normal)
print("\nForma del arreglo:", a_normal.shape)

Arreglo de 15 números con distribución normal estándar:
[-1.02056810e+00  7.72199730e-01 -2.57593806e-02  2.50800850e-01
 -1.36063956e-03 -1.57904630e+00  1.50082127e-02 -2.57120043e-01
 -1.04532451e-01  2.42894696e-02  1.96506240e-01  2.09385989e+00
  1.07661990e+00 -6.23602949e-01  9.71475220e-01]

Forma del arreglo: (15,)


In [16]:
# ejercicio 14

a = np.arange(15, 56)

print("Arreglo completo (15 a 55):")
print(a)
print("-" * 60)

resultado_ = a[1:-1]

print("Valores intermedios (excluyendo 15 y 55):")
print(resultado_)

Arreglo completo (15 a 55):
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
------------------------------------------------------------
Valores intermedios (excluyendo 15 y 55):
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [18]:
# ejercicio 15

a = np.linspace(5, 50, 10)

print("Arreglo de 10 valores equitativamente distribuidos:")
print(a)
print("\nForma del arreglo (longitud):", a.shape)

Arreglo de 10 valores equitativamente distribuidos:
[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]

Forma del arreglo (longitud): (10,)


In [19]:
# ejercicio 16

vector = np.arange(0, 21)
print("Vector original (0 a 20):")
print(vector)
print("-" * 60)

condicion = (vector >= 9) & (vector <= 15)

vector[condicion] = vector[condicion] * -1

print("Vector con signo cambiado (9 a 15):")
print(vector)

Vector original (0 a 20):
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
------------------------------------------------------------
Vector con signo cambiado (9 a 15):
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [20]:
# ejercicio 17 

a = np.array([1, 2, 3])
print("Arreglo original (Tipo):", type(a))

lista_python = a.tolist()

print("Lista de Python (Resultado):", lista_python)
print("Tipo del resultado:", type(lista_python))

Arreglo original (Tipo): <class 'numpy.ndarray'>
Lista de Python (Resultado): [1, 2, 3]
Tipo del resultado: <class 'list'>


In [21]:
# ejercicio 18 

# 1. Definir la lista nativa de Python
l = [1, 2, 3]
print("Objeto original (Tipo):", type(l))

# 2. Convertir la lista a un arreglo de NumPy usando np.array()
arreglo_numpy = np.array(l)

print("Arreglo de NumPy (Resultado):", arreglo_numpy)
print("Tipo del resultado:", type(arreglo_numpy))

Objeto original (Tipo): <class 'list'>
Arreglo de NumPy (Resultado): [1 2 3]
Tipo del resultado: <class 'numpy.ndarray'>


In [ ]:
# ejercicio 19
#  1. Definir la matriz original
m = np.array([[1, 2], [3, 4]])
print("Matriz original m:")
print(m)
print("-" * 30)

# 2. Verificar la paridad usando el operador módulo (%)
# La condición (m % 2 == 0) devuelve True para todos los números que son divisibles por 2 (pares).
matriz_booleana = (m % 2 == 0)

# 3. Almacenar los resultados en otra matriz (la matriz booleana)
# El resultado es una nueva matriz booleana con las mismas dimensiones que m.
print("Matriz de resultados (True = Par, False = Impar):")
print(matriz_booleana)

Matriz original m:
[[1 2]
 [3 4]]
------------------------------
Matriz de resultados (True = Par, False = Impar):
[[False  True]
 [False  True]]


In [ ]:
# ejercicio 20 
# 1. Definir la matriz
m = np.array([[1, 2, 3], [4, 5, 6]])

# 2. Encontrar la forma de la matriz (filas, columnas) usando .shape
filas, columnas = m.shape

print("Matriz m:")
print(m)
print("-" * 30)
print(f"Forma de la matriz (m.shape): {m.shape}")
print(f"Número de filas: {filas}")
print(f"Número de columnas: {columnas}")

Matriz m:
[[1 2 3]
 [4 5 6]]
------------------------------
Forma de la matriz (m.shape): (2, 3)
Número de filas: 2
Número de columnas: 3
